spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://recorder-db.coc4nogghmiq.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: recorder
    password: fpzhej1234!

cloud:
  aws:
    s3:
      bucket: myrecorderbucket
#      folder:
#        [VARIABLE]: [VALUE]
    region:
      static: ap-northeast-1
    stack:
      auto: false

    credentials:
      accessKey: AKIAYDAEPXYPPLMLN2YH
      secretKey: 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